version: '3.8'
services:
  mongodb:
    image: mongo:latest
    environment:
      - MONGODB_DATABASE="test"
    ports:
      - 27017:27017  

  nestserver: 
    build: .
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - ${APP_PORT}:${APP_PORT}
    command: npm run start:dev
    env_file:
      - .env
    depends_on:
      - mongodb

  nginx:
    restart: always
    build:
      context: ./nginx
    ports:
      - "8080:80"

volumes:
  mongodb_data_container:

networks:
  app-net:
    driver: bridge
